### ISSUE TITLE
Help on workers IS a worker or chain of workers (500 cow points)

### ISSUE THREAD

**Issue by brifordwylie** [SuperCowPowers/old-workbench-archived#242]
So the current clumsiness around processing doc strings one way for python client and one way for CLI client illuminates the need for generalization of the process into workers. This work will include an important addition to the docstring for every worker. Docstrings will now contain an optional 'sematics' section. Any field that is 'something more' than just its type, can be called out. 

```
class SuperComplicatedOutput():
    """ I'm a google compliant docstring
         Args:
              foo: Instance of foo
              bar: list of bars
              labels: labels for the foo.
         Returns:
             foo_a: blah blah
             foo_z:  blah blah
             offset:  blah blah
             heap: blah blah
         Semantics:
              offset: memory_pointer_offset
              heap: memory_pointer
    """
```
- 'workers' collection in the database will store the dynamically loaded docstrings
- you can just pull it directly
- for CLI version you pull from the doc_to_cli worker.
- for HTML version you pull from the doc_to_html worker
- for presentation/styling you can pull a style from the 'css' collection

The 'css' collection will hold styling 'treatments' for the html that comes from the doc_to_html worker.
